#FROM docker.io/gentoo/portage:20240220 as portage
FROM docker.io/gentoo/portage:20240229 as portage
#FROM docker.io/gentoo/stage3:20240219
FROM docker.io/gentoo/stage3:20240226

# copy the entire portage volume in
COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo

RUN emerge -v --noreplace dev-vcs/git
RUN emerge -v1u portage

# Pinned commits for the dependency tree state
#ARG gentoo_hash=973aecd3315d2651f3977e13970ccdc155ae8304
#ARG science_hash=a9c44ac79d03faa7d3dd7841c6ea96b7017830f5
ARG gentoo_hash=e0226bb33e74851ac96f181ae9bf43f60e7e991c
ARG science_hash=a28423309bc3562113676a5009af778a18447267
ARG FEATURES="-ipc-sandbox -network-sandbox -pid-sandbox"

# This will be bound, and contents available outside of container
#RUN mkdir /outputs

COPY . /opt/SAMRI
#RUN ls -lah /opt/SAMRI
COPY .gentoo/portage/ /etc/portage/
COPY .gentoo/overlay/ /var/db/repos/local/
#RUN ls -lah /etc/portage
#RUN ls -lah /var/db/repos/local/

# Moving gentoo repo from default rsync to git
RUN rm /var/db/repos/gentoo -rf

# Disable auto-sync
RUN sed -i /etc/portage/repos.conf/{gentoo,science} -e "s/sync-type *= *git/sync-type =/g"

# Cloning manually to prevent vdb update, pinning state via git
#RUN REPO_URL=$(grep "^sync-uri" /etc/portage/repos.conf/gentoo | sed -e "s/sync-uri *= *//g"); mkdir -p /var/db/repos/gentoo; pushd /var/db/repos/gentoo; git clone ${REPO_URL} .; git fetch origin $gentoo_hash; git checkout $gentoo_hash; rm .git -rf; popd
#RUN REPO_URL=$(grep "^sync-uri" /etc/portage/repos.conf/science | sed -e "s/sync-uri *= *//g"); mkdir -p /var/db/repos/science; pushd /var/db/repos/science; git clone ${REPO_URL} .; git fetch origin $science_hash; git checkout $science_hash; rm .git -rf; popd
RUN 	REPO_URL=$(grep "^sync-uri" /etc/portage/repos.conf/gentoo | sed -e "s/sync-uri *= *//g"); mkdir -p /var/db/repos/gentoo; pushd /var/db/repos/gentoo; git clone ${REPO_URL} .; git fetch origin $gentoo_hash; git checkout $gentoo_hash; rm .git -rf; popd && \
	REPO_URL=$(grep "^sync-uri" /etc/portage/repos.conf/science | sed -e "s/sync-uri *= *//g"); mkdir -p /var/db/repos/science; pushd /var/db/repos/science; git clone ${REPO_URL} .; git fetch origin $science_hash; git checkout $science_hash; rm .git -rf; popd

# Remove sync-uri for consistency
RUN sed -i /etc/portage/repos.conf/{gentoo,science} -e "/sync-uri/d"
RUN sed -i /etc/portage/repos.conf/{gentoo,science} -e "/sync-git-verify-commit-signature/d"

# Ensure Umask-safe permissions
RUN chmod -R a+rX /var/db/repos/local*/

# Make sure all CPU flags supported by the hardware are whitelisted
# This only affects packages with handwritten assembly language optimizations, e.g. ffmpeg.
# Removing it is safe, software will just not take full advantage of processor capabilities.
#RUN eselect profile set 1
RUN emerge cpuid2cpuflags
RUN echo "*/* $(cpuid2cpuflags)" > /etc/portage/package.use/00cpu-flags

# Dynamically prepare manifest and go crazy.
RUN my_ebuild=$(/bin/ls -1 /var/db/repos/local/sci-biology/*/*99999.ebuild) && \
	ebuild "$my_ebuild" manifest && \
	export DOTGENTOO_PACKAGE_ROOT=/opt/SAMRI && \
	emerge -v $(echo $my_ebuild | sed -e 's,.*/\([-_0-9a-zA-Z]*\)-99999.ebuild,\1,g') --autounmask-continue && \
	rm -rf /var/cache/distfiles/

#RUN my_ebuild=$(/bin/ls -1 /var/db/repos/local/sci-misc/*/*99999.ebuild) && \
#	ebuild "$my_ebuild"  manifest
#ENTRYPOINT ["/bin/bash"]
