from samri.optimization.newreg import single_generic

NEWPHASES = {
	"f_rigid":{
		"transforms":"Rigid",
		"transform_parameters":(0.1,),
		"number_of_iterations":[300],
		"metric":"MI",
		"metric_weight":1,
		"radius_or_number_of_bins":32,
		"sampling_strategy":"Regular",
		"sampling_percentage":0.5,
		"convergence_threshold":1.e-8,
		"convergence_window_size":10,
		"smoothing_sigmas":[0],
		"sigma_units":"vox",
		"shrink_factors":[1],
		"use_estimate_learning_rate_once":False,
		"use_histogram_matching":False,
		},
	"s_rigid":{
		"transforms":"Rigid",
		"transform_parameters":(0.1,),
		"number_of_iterations":[2000,3000],
		"metric":"GC",
		"metric_weight":1,
		"radius_or_number_of_bins":64,
		"sampling_strategy":"Regular",
		"sampling_percentage":0.2,
		"convergence_threshold":1.e-16,
		"convergence_window_size":30,
		"smoothing_sigmas":[1,0],
		"sigma_units":"vox",
		"shrink_factors":[2,1],
		"use_estimate_learning_rate_once":False,
		"use_histogram_matching":True,
		},
	"affine":{
		"transforms":"Affine",
		"transform_parameters":(0.1,),
		"number_of_iterations":[200,100],
		"metric":"MI",
		"metric_weight":1,
		"radius_or_number_of_bins":64,
		"sampling_strategy":'Regular',
		"sampling_percentage":0.2,
		"convergence_threshold":1.e-8,
		"convergence_window_size":10,
		"smoothing_sigmas":[1,0],
		"sigma_units":"vox",
		"shrink_factors":[1,1],
		"use_estimate_learning_rate_once":False,
		"use_histogram_matching":True,
		},
	"syn":{
		"transforms":"SyN",
		"transform_parameters":(0.1, 2.0, 0.2),
		"number_of_iterations":[500,250],
		"metric":"MI",
		"metric_weight":1,
		"radius_or_number_of_bins":16,
		"sampling_strategy":None,
		"sampling_percentage":0.3,
		"convergence_threshold":1.e-32,
		"convergence_window_size":30,
		"smoothing_sigmas":[1,0],
		"sigma_units":"vox",
		"shrink_factors":[1,1],
		"use_estimate_learning_rate_once":False,
		"use_histogram_matching":True,
		},
	}
TEST_PHASES = {
	"f_rigid":{
		"transforms":"Rigid",
		"transform_parameters":(0.1,),
		"number_of_iterations":[80],
		"metric":"MI",
		"metric_weight":1,
		"radius_or_number_of_bins":32,
		"sampling_strategy":"Regular",
		"sampling_percentage":0.1,
		"convergence_threshold":1.e-8,
		"convergence_window_size":10,
		"smoothing_sigmas":[0],
		"sigma_units":"vox",
		"shrink_factors":[1],
		"use_estimate_learning_rate_once":False,
		"use_histogram_matching":False,
		},
	"s_rigid":{
		"transforms":"Rigid",
		"transform_parameters":(0.1,),
		"number_of_iterations":[40,80],
		"metric":"GC",
		"metric_weight":1,
		"radius_or_number_of_bins":64,
		"sampling_strategy":"Regular",
		"sampling_percentage":0.1,
		"convergence_threshold":1.e-8,
		"convergence_window_size":10,
		"smoothing_sigmas":[1,0],
		"sigma_units":"vox",
		"shrink_factors":[2,1],
		"use_estimate_learning_rate_once":False,
		"use_histogram_matching":True,
		},
	"affine":{
		"transforms":"Affine",
		"transform_parameters":(0.1,),
		"number_of_iterations":[80,40],
		"metric":"MI",
		"metric_weight":1,
		"radius_or_number_of_bins":64,
		"sampling_strategy":'Regular',
		"sampling_percentage":0.1,
		"convergence_threshold":1.e-8,
		"convergence_window_size":10,
		"smoothing_sigmas":[1,0],
		"sigma_units":"vox",
		"shrink_factors":[1,1],
		"use_estimate_learning_rate_once":False,
		"use_histogram_matching":True,
		},
	"syn":{
		"transforms":"SyN",
		"transform_parameters":(0.1, 2.0, 0.2),
		"number_of_iterations":[80,40],
		"metric":"MI",
		"metric_weight":1,
		"radius_or_number_of_bins":16,
		"sampling_strategy":None,
		"sampling_percentage":0.1,
		"convergence_threshold":1.e-8,
		"convergence_window_size":10,
		"smoothing_sigmas":[1,0],
		"sigma_units":"vox",
		"shrink_factors":[1,1],
		"use_estimate_learning_rate_once":False,
		"use_histogram_matching":True,
		},
	}

def test_single_generic():
	single_generic(
		'/usr/share/samri_bidsdata/bids/sub-4007/ses-ofM/func/sub-4007_ses-ofM_task-JogB_acq-EPIlowcov_run-1_cbv.nii.gz',
		'/usr/share/samri_bidsdata/bids/sub-4007/ses-ofM/anat/sub-4007_ses-ofM_acq-TurboRARElowcov_T2w.nii.gz',
		'/usr/share/mouse-brain-atlases/dsurqec_200micron.nii',
		mask='/usr/share/mouse-brain-atlases/dsurqec_200micron_mask.nii',
		phases=TEST_PHASES,
		s_phases=['s_rigid','affine','syn'],
		f_phases=['f_rigid'],
		)
#single_generic(
#	'~/ni_data/ofM.dr/bids_collapsed/sub-4001/ses-ofMcf"/func/sub-4001_ses-ofMcF2_task-JogB_acq-EPIlowcov_run-1_cbv.nii.gz',
#	'~/ni_data/ofM.dr/bids_collapsed/sub-4001/ses-ofMcF2/anat/sub-4001_ses-ofMcF2_acq-TurboRARElowcov_T2w.nii.gz',
#	'/usr/share/mouse-brain-atlases/dsurqec_200micron.nii',
#	mask='/usr/share/mouse-brain-atlases/dsurqec_200micron_mask.nii',
#	phases=NEWPHASES,
#	s_phases=['s_rigid','affine','syn'],
#	f_phases=['f_rigid'],
#	)
